[project]
name = "cobalt-backend"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "cryptography>=50.0.0",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pydantic>=2.13.4",
    "pydantic-extra-types>=2.11.1",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-httpx>=0.36.2",
    "starlette>=1.6.0",
    "uvicorn>=0.52.4",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode = "auto"
